`timescale 1ns / 1ps

module stage4_real_internal_key_two_way_merge_stage5_chain_top #(
    parameter integer AXI_ADDR_WIDTH              = 64,
    parameter integer AXI_DATA_WIDTH              = 512,
    parameter integer AXI_ID_WIDTH                = 1,
    parameter integer MAX_BURST_LEN               = 16,
    parameter integer STAGE4_MAX_BLOCK_BYTES      = 4096,
    parameter integer STAGE4_MAX_KEY_BYTES        = 264,
    parameter integer MERGE_MAX_USER_KEY_BYTES    = 256,
    parameter integer MERGE_MAX_KEY_BYTES         = 264,
    parameter integer MERGE_MAX_VALUE_BYTES       = 1024,
    parameter integer MERGE_MAX_RECORD_BYTES      = 2048,
    parameter integer MERGE_MAX_RECORDS           = 256,
    parameter integer MERGE_MAX_OUTPUT_BYTES      = 73728,
    parameter integer STAGE5_MAX_RECORDS          = 256,
    parameter integer STAGE5_MAX_PAYLOAD_BYTES    = 4096,
    parameter integer STAGE5_MAX_BLOCK_BYTES      = 4096,
    parameter integer STAGE5_MAX_KEY_BYTES        = 256,
    parameter integer STAGE5_MAX_VALUE_BYTES      = 1024,
    parameter integer STAGE5_RESTART_INTERVAL     = 16
) (
    input  wire                          clk,
    input  wire                          rstn,
    input  wire                          clear,
    input  wire                          start,
    input  wire                          seed_prev_user_key_valid,
    input  wire [15:0]                   seed_prev_user_key_len,
    input  wire [(MERGE_MAX_USER_KEY_BYTES*8)-1:0] seed_prev_user_key,
    input  wire [AXI_ADDR_WIDTH-1:0]     src0_base_addr,
    input  wire [31:0]                   src0_byte_count,
    input  wire [AXI_ADDR_WIDTH-1:0]     src1_base_addr,
    input  wire [31:0]                   src1_byte_count,
    input  wire [AXI_ADDR_WIDTH-1:0]     mid_base_addr,
    input  wire [AXI_ADDR_WIDTH-1:0]     dst_base_addr,
    output wire                          busy,
    output wire                          done,
    output wire                          error,
    output wire [31:0]                   source0_decoded_entry_count,
    output wire [31:0]                   source0_restart_count,
    output wire [31:0]                   source0_restart_entry_count,
    output wire [31:0]                   source0_shared_key_bytes_total,
    output wire [31:0]                   source0_unshared_key_bytes_total,
    output wire [31:0]                   source0_value_bytes_total,
    output wire [15:0]                   source0_last_key_len,
    output wire [15:0]                   source0_last_value_len,
    output wire [15:0]                   source0_last_shared_bytes,
    output wire [15:0]                   source0_last_non_shared_bytes,
    output wire [31:0]                   source0_restart_array_offset,
    output wire [31:0]                   source0_bytes_read,
    output wire [31:0]                   source0_beats_read,
    output wire [31:0]                   source1_decoded_entry_count,
    output wire [31:0]                   source1_restart_count,
    output wire [31:0]                   source1_restart_entry_count,
    output wire [31:0]                   source1_shared_key_bytes_total,
    output wire [31:0]                   source1_unshared_key_bytes_total,
    output wire [31:0]                   source1_value_bytes_total,
    output wire [15:0]                   source1_last_key_len,
    output wire [15:0]                   source1_last_value_len,
    output wire [15:0]                   source1_last_shared_bytes,
    output wire [15:0]                   source1_last_non_shared_bytes,
    output wire [31:0]                   source1_restart_array_offset,
    output wire [31:0]                   source1_bytes_read,
    output wire [31:0]                   source1_beats_read,
    output wire [31:0]                   merge_bytes_written,
    output wire [31:0]                   merge_beats_written,
    output wire [31:0]                   merge_output_byte_count,
    output wire [31:0]                   merge_decoded_record_count,
    output wire [31:0]                   merge_merged_record_count,
    output wire [31:0]                   merge_dropped_superseded_count,
    output wire [31:0]                   merge_value_record_count,
    output wire [31:0]                   merge_delete_record_count,
    output wire [31:0]                   merge_user_key_bytes_total,
    output wire [31:0]                   merge_value_bytes_total,
    output wire [15:0]                   merge_last_user_key_len,
    output wire [55:0]                   merge_last_sequence,
    output wire [7:0]                    merge_last_value_type,
    output wire                          merge_last_record_keep,
    output wire [31:0]                   stage5_bytes_read,
    output wire [31:0]                   stage5_beats_read,
    output wire [31:0]                   stage5_bytes_written,
    output wire [31:0]                   stage5_beats_written,
    output wire [31:0]                   stage5_input_record_count,
    output wire [31:0]                   stage5_encoded_entry_count,
    output wire [31:0]                   stage5_restart_count,
    output wire [31:0]                   stage5_shared_key_bytes_total,
    output wire [31:0]                   stage5_unshared_key_bytes_total,
    output wire [31:0]                   stage5_value_bytes_total,
    output wire [15:0]                   stage5_last_key_len,
    output wire [15:0]                   stage5_last_value_len,
    output wire [15:0]                   stage5_last_shared_bytes,
    output wire [15:0]                   stage5_last_non_shared_bytes,
    output wire [31:0]                   stage5_output_block_bytes,
    output wire                          final_prev_user_key_valid,
    output wire [15:0]                   final_prev_user_key_len,
    output wire [(MERGE_MAX_USER_KEY_BYTES*8)-1:0] final_prev_user_key,

    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_src0_araddr,
    output wire [7:0]                    m_axi_src0_arlen,
    output wire [2:0]                    m_axi_src0_arsize,
    output wire [1:0]                    m_axi_src0_arburst,
    output wire                          m_axi_src0_arvalid,
    input  wire                          m_axi_src0_arready,
    input  wire [AXI_DATA_WIDTH-1:0]     m_axi_src0_rdata,
    input  wire [1:0]                    m_axi_src0_rresp,
    input  wire                          m_axi_src0_rlast,
    input  wire                          m_axi_src0_rvalid,
    output wire                          m_axi_src0_rready,

    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_src1_araddr,
    output wire [7:0]                    m_axi_src1_arlen,
    output wire [2:0]                    m_axi_src1_arsize,
    output wire [1:0]                    m_axi_src1_arburst,
    output wire                          m_axi_src1_arvalid,
    input  wire                          m_axi_src1_arready,
    input  wire [AXI_DATA_WIDTH-1:0]     m_axi_src1_rdata,
    input  wire [1:0]                    m_axi_src1_rresp,
    input  wire                          m_axi_src1_rlast,
    input  wire                          m_axi_src1_rvalid,
    output wire                          m_axi_src1_rready,

    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_chain_araddr,
    output wire [7:0]                    m_axi_chain_arlen,
    output wire [2:0]                    m_axi_chain_arsize,
    output wire [1:0]                    m_axi_chain_arburst,
    output wire                          m_axi_chain_arvalid,
    input  wire                          m_axi_chain_arready,
    input  wire [AXI_DATA_WIDTH-1:0]     m_axi_chain_rdata,
    input  wire [1:0]                    m_axi_chain_rresp,
    input  wire                          m_axi_chain_rlast,
    input  wire                          m_axi_chain_rvalid,
    output wire                          m_axi_chain_rready,
    output wire [AXI_ADDR_WIDTH-1:0]     m_axi_chain_awaddr,
    output wire [7:0]                    m_axi_chain_awlen,
    output wire [2:0]                    m_axi_chain_awsize,
    output wire [1:0]                    m_axi_chain_awburst,
    output wire                          m_axi_chain_awvalid,
    input  wire                          m_axi_chain_awready,
    output wire [AXI_DATA_WIDTH-1:0]     m_axi_chain_wdata,
    output wire [(AXI_DATA_WIDTH/8)-1:0] m_axi_chain_wstrb,
    output wire                          m_axi_chain_wlast,
    output wire                          m_axi_chain_wvalid,
    input  wire                          m_axi_chain_wready,
    input  wire [1:0]                    m_axi_chain_bresp,
    input  wire                          m_axi_chain_bvalid,
    output wire                          m_axi_chain_bready
);

    wire        source0_busy_i;
    wire        source0_done_i;
    wire        source0_error_i;
    wire        s0_record_valid_i;
    wire        s0_record_ready_i;
    wire [15:0] s0_record_key_len_i;
    wire [15:0] s0_record_value_len_i;
    wire [15:0] s0_record_shared_bytes_i;
    wire [15:0] s0_record_non_shared_bytes_i;
    wire [7:0]  s0_record_tdata_i;
    wire [0:0]  s0_record_tkeep_i;
    wire        s0_record_tlast_i;
    wire        s0_record_tvalid_i;
    wire        s0_record_tready_i;

    wire        source1_busy_i;
    wire        source1_done_i;
    wire        source1_error_i;
    wire        s1_record_valid_i;
    wire        s1_record_ready_i;
    wire [15:0] s1_record_key_len_i;
    wire [15:0] s1_record_value_len_i;
    wire [15:0] s1_record_shared_bytes_i;
    wire [15:0] s1_record_non_shared_bytes_i;
    wire [7:0]  s1_record_tdata_i;
    wire [0:0]  s1_record_tkeep_i;
    wire        s1_record_tlast_i;
    wire        s1_record_tvalid_i;
    wire        s1_record_tready_i;

    wire chain_busy_i;
    wire chain_done_i;
    wire chain_error_i;
    wire chain_merge_done_i;
    wire chain_stage5_done_i;

    stage4_real_data_block_record_emit_top #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN),
        .MAX_BLOCK_BYTES(STAGE4_MAX_BLOCK_BYTES),
        .MAX_KEY_BYTES(STAGE4_MAX_KEY_BYTES)
    ) u_source0_emit (
        .clk(clk),
        .rstn(rstn),
        .clear(clear),
        .start(start),
        .src_base_addr(src0_base_addr),
        .byte_count(src0_byte_count),
        .busy(source0_busy_i),
        .done(source0_done_i),
        .error(source0_error_i),
        .bytes_read(source0_bytes_read),
        .beats_read(source0_beats_read),
        .record_valid(s0_record_valid_i),
        .record_ready(s0_record_ready_i),
        .record_key_len(s0_record_key_len_i),
        .record_value_len(s0_record_value_len_i),
        .record_shared_bytes(s0_record_shared_bytes_i),
        .record_non_shared_bytes(s0_record_non_shared_bytes_i),
        .record_tdata(s0_record_tdata_i),
        .record_tkeep(s0_record_tkeep_i),
        .record_tlast(s0_record_tlast_i),
        .record_tvalid(s0_record_tvalid_i),
        .record_tready(s0_record_tready_i),
        .decoded_entry_count(source0_decoded_entry_count),
        .restart_count(source0_restart_count),
        .restart_entry_count(source0_restart_entry_count),
        .shared_key_bytes_total(source0_shared_key_bytes_total),
        .unshared_key_bytes_total(source0_unshared_key_bytes_total),
        .value_bytes_total(source0_value_bytes_total),
        .last_key_len(source0_last_key_len),
        .last_value_len(source0_last_value_len),
        .last_shared_bytes(source0_last_shared_bytes),
        .last_non_shared_bytes(source0_last_non_shared_bytes),
        .restart_array_offset(source0_restart_array_offset),
        .m_axi_araddr(m_axi_src0_araddr),
        .m_axi_arlen(m_axi_src0_arlen),
        .m_axi_arsize(m_axi_src0_arsize),
        .m_axi_arburst(m_axi_src0_arburst),
        .m_axi_arid(),
        .m_axi_arvalid(m_axi_src0_arvalid),
        .m_axi_arready(m_axi_src0_arready),
        .m_axi_rdata(m_axi_src0_rdata),
        .m_axi_rresp(m_axi_src0_rresp),
        .m_axi_rlast(m_axi_src0_rlast),
        .m_axi_rid({AXI_ID_WIDTH{1'b0}}),
        .m_axi_rvalid(m_axi_src0_rvalid),
        .m_axi_rready(m_axi_src0_rready)
    );

    stage4_real_data_block_record_emit_top #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN),
        .MAX_BLOCK_BYTES(STAGE4_MAX_BLOCK_BYTES),
        .MAX_KEY_BYTES(STAGE4_MAX_KEY_BYTES)
    ) u_source1_emit (
        .clk(clk),
        .rstn(rstn),
        .clear(clear),
        .start(start),
        .src_base_addr(src1_base_addr),
        .byte_count(src1_byte_count),
        .busy(source1_busy_i),
        .done(source1_done_i),
        .error(source1_error_i),
        .bytes_read(source1_bytes_read),
        .beats_read(source1_beats_read),
        .record_valid(s1_record_valid_i),
        .record_ready(s1_record_ready_i),
        .record_key_len(s1_record_key_len_i),
        .record_value_len(s1_record_value_len_i),
        .record_shared_bytes(s1_record_shared_bytes_i),
        .record_non_shared_bytes(s1_record_non_shared_bytes_i),
        .record_tdata(s1_record_tdata_i),
        .record_tkeep(s1_record_tkeep_i),
        .record_tlast(s1_record_tlast_i),
        .record_tvalid(s1_record_tvalid_i),
        .record_tready(s1_record_tready_i),
        .decoded_entry_count(source1_decoded_entry_count),
        .restart_count(source1_restart_count),
        .restart_entry_count(source1_restart_entry_count),
        .shared_key_bytes_total(source1_shared_key_bytes_total),
        .unshared_key_bytes_total(source1_unshared_key_bytes_total),
        .value_bytes_total(source1_value_bytes_total),
        .last_key_len(source1_last_key_len),
        .last_value_len(source1_last_value_len),
        .last_shared_bytes(source1_last_shared_bytes),
        .last_non_shared_bytes(source1_last_non_shared_bytes),
        .restart_array_offset(source1_restart_array_offset),
        .m_axi_araddr(m_axi_src1_araddr),
        .m_axi_arlen(m_axi_src1_arlen),
        .m_axi_arsize(m_axi_src1_arsize),
        .m_axi_arburst(m_axi_src1_arburst),
        .m_axi_arid(),
        .m_axi_arvalid(m_axi_src1_arvalid),
        .m_axi_arready(m_axi_src1_arready),
        .m_axi_rdata(m_axi_src1_rdata),
        .m_axi_rresp(m_axi_src1_rresp),
        .m_axi_rlast(m_axi_src1_rlast),
        .m_axi_rid({AXI_ID_WIDTH{1'b0}}),
        .m_axi_rvalid(m_axi_src1_rvalid),
        .m_axi_rready(m_axi_src1_rready)
    );

    real_internal_key_two_way_merge_stage5_chain_top #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN),
        .MERGE_MAX_USER_KEY_BYTES(MERGE_MAX_USER_KEY_BYTES),
        .MERGE_MAX_KEY_BYTES(MERGE_MAX_KEY_BYTES),
        .MERGE_MAX_VALUE_BYTES(MERGE_MAX_VALUE_BYTES),
        .MERGE_MAX_RECORD_BYTES(MERGE_MAX_RECORD_BYTES),
        .MERGE_MAX_RECORDS(MERGE_MAX_RECORDS),
        .MERGE_MAX_OUTPUT_BYTES(MERGE_MAX_OUTPUT_BYTES),
        .STAGE5_MAX_RECORDS(STAGE5_MAX_RECORDS),
        .STAGE5_MAX_PAYLOAD_BYTES(STAGE5_MAX_PAYLOAD_BYTES),
        .STAGE5_MAX_BLOCK_BYTES(STAGE5_MAX_BLOCK_BYTES),
        .STAGE5_MAX_KEY_BYTES(STAGE5_MAX_KEY_BYTES),
        .STAGE5_MAX_VALUE_BYTES(STAGE5_MAX_VALUE_BYTES),
        .STAGE5_RESTART_INTERVAL(STAGE5_RESTART_INTERVAL)
    ) u_two_way_chain (
        .clk(clk),
        .rstn(rstn),
        .clear(clear),
        .start(start),
        .seed_prev_user_key_valid(seed_prev_user_key_valid),
        .seed_prev_user_key_len(seed_prev_user_key_len),
        .seed_prev_user_key(seed_prev_user_key),
        .source0_done(source0_done_i),
        .s0_record_valid(s0_record_valid_i),
        .s0_record_ready(s0_record_ready_i),
        .s0_record_key_len(s0_record_key_len_i),
        .s0_record_value_len(s0_record_value_len_i),
        .s0_axis_tdata(s0_record_tdata_i),
        .s0_axis_tkeep(s0_record_tkeep_i),
        .s0_axis_tlast(s0_record_tlast_i),
        .s0_axis_tvalid(s0_record_tvalid_i),
        .s0_axis_tready(s0_record_tready_i),
        .source1_done(source1_done_i),
        .s1_record_valid(s1_record_valid_i),
        .s1_record_ready(s1_record_ready_i),
        .s1_record_key_len(s1_record_key_len_i),
        .s1_record_value_len(s1_record_value_len_i),
        .s1_axis_tdata(s1_record_tdata_i),
        .s1_axis_tkeep(s1_record_tkeep_i),
        .s1_axis_tlast(s1_record_tlast_i),
        .s1_axis_tvalid(s1_record_tvalid_i),
        .s1_axis_tready(s1_record_tready_i),
        .mid_base_addr(mid_base_addr),
        .dst_base_addr(dst_base_addr),
        .busy(chain_busy_i),
        .done(chain_done_i),
        .error(chain_error_i),
        .merge_done(chain_merge_done_i),
        .stage5_done(chain_stage5_done_i),
        .merge_bytes_written(merge_bytes_written),
        .merge_beats_written(merge_beats_written),
        .merge_output_byte_count(merge_output_byte_count),
        .merge_decoded_record_count(merge_decoded_record_count),
        .merge_merged_record_count(merge_merged_record_count),
        .merge_dropped_superseded_count(merge_dropped_superseded_count),
        .merge_value_record_count(merge_value_record_count),
        .merge_delete_record_count(merge_delete_record_count),
        .merge_user_key_bytes_total(merge_user_key_bytes_total),
        .merge_value_bytes_total(merge_value_bytes_total),
        .merge_last_user_key_len(merge_last_user_key_len),
        .merge_last_sequence(merge_last_sequence),
        .merge_last_value_type(merge_last_value_type),
        .merge_last_record_keep(merge_last_record_keep),
        .stage5_bytes_read(stage5_bytes_read),
        .stage5_beats_read(stage5_beats_read),
        .stage5_bytes_written(stage5_bytes_written),
        .stage5_beats_written(stage5_beats_written),
        .stage5_input_record_count(stage5_input_record_count),
        .stage5_encoded_entry_count(stage5_encoded_entry_count),
        .stage5_restart_count(stage5_restart_count),
        .stage5_shared_key_bytes_total(stage5_shared_key_bytes_total),
        .stage5_unshared_key_bytes_total(stage5_unshared_key_bytes_total),
        .stage5_value_bytes_total(stage5_value_bytes_total),
        .stage5_last_key_len(stage5_last_key_len),
        .stage5_last_value_len(stage5_last_value_len),
        .stage5_last_shared_bytes(stage5_last_shared_bytes),
        .stage5_last_non_shared_bytes(stage5_last_non_shared_bytes),
        .stage5_output_block_bytes(stage5_output_block_bytes),
        .final_prev_user_key_valid(final_prev_user_key_valid),
        .final_prev_user_key_len(final_prev_user_key_len),
        .final_prev_user_key(final_prev_user_key),
        .m_axi_araddr(m_axi_chain_araddr),
        .m_axi_arlen(m_axi_chain_arlen),
        .m_axi_arsize(m_axi_chain_arsize),
        .m_axi_arburst(m_axi_chain_arburst),
        .m_axi_arid(),
        .m_axi_arvalid(m_axi_chain_arvalid),
        .m_axi_arready(m_axi_chain_arready),
        .m_axi_rdata(m_axi_chain_rdata),
        .m_axi_rresp(m_axi_chain_rresp),
        .m_axi_rlast(m_axi_chain_rlast),
        .m_axi_rid({AXI_ID_WIDTH{1'b0}}),
        .m_axi_rvalid(m_axi_chain_rvalid),
        .m_axi_rready(m_axi_chain_rready),
        .m_axi_awaddr(m_axi_chain_awaddr),
        .m_axi_awlen(m_axi_chain_awlen),
        .m_axi_awsize(m_axi_chain_awsize),
        .m_axi_awburst(m_axi_chain_awburst),
        .m_axi_awid(),
        .m_axi_awvalid(m_axi_chain_awvalid),
        .m_axi_awready(m_axi_chain_awready),
        .m_axi_wdata(m_axi_chain_wdata),
        .m_axi_wstrb(m_axi_chain_wstrb),
        .m_axi_wlast(m_axi_chain_wlast),
        .m_axi_wvalid(m_axi_chain_wvalid),
        .m_axi_wready(m_axi_chain_wready),
        .m_axi_bresp(m_axi_chain_bresp),
        .m_axi_bid({AXI_ID_WIDTH{1'b0}}),
        .m_axi_bvalid(m_axi_chain_bvalid),
        .m_axi_bready(m_axi_chain_bready)
    );

    assign busy  = source0_busy_i | source1_busy_i | chain_busy_i;
    assign done  = chain_done_i;
    assign error = source0_error_i | source1_error_i | chain_error_i;

endmodule
