`timescale 1ns / 1ps
// tb_sstable_parser_top
//
// Verifies sstable_data_block_handle_emitter against real LevelDB SSTable
// fixtures generated by gen_test_sstable.py.
//
// Expected values are hardcoded from the generator output; update them after
// re-running the generator if the fixture changes.
//
// Fixture layout:
//   SRC0 SSTable: loaded into mem_p0.mem[] at address 0x0000 (via @00000000)
//   SRC1 SSTable: loaded into mem_p1.mem[] at address 0x4000 (via @00004000)
//
// Expected (from gen_test_sstable.py):
//   src0: 2 blocks, block[0] addr=0x0000  size=123
//                   block[1] addr=0x0080  size=123   sstable_size=373
//   src1: 2 blocks, block[0] addr=0x4000  size=122
//                   block[1] addr=0x407f  size=63    sstable_size=311
//
module tb_sstable_parser_top;

    localparam integer AXI_ADDR_WIDTH    = 64;
    localparam integer AXI_DATA_WIDTH    = 512;
    localparam integer MAX_BURST_LEN     = 16;
    localparam integer MAX_INDEX_BYTES   = 8192;
    localparam integer MAX_BLOCK_HANDLES = 8;
    localparam integer MEM_BYTES         = 32768;   // 32 KB per RAM instance

    localparam [63:0] SRC0_BASE = 64'h0000_0000_0000_0000;
    localparam [63:0] SRC1_BASE = 64'h0000_0000_0000_4000;

    // -- expected values (hardcoded from generator output) -----------------
    localparam integer EXP_P0_COUNT  = 2;
    localparam integer EXP_P0_SIZE   = 373;
    localparam [63:0] EXP_P0_ADDR0  = 64'h0000_0000_0000_0000;
    localparam [31:0] EXP_P0_BSIZ0  = 32'd123;
    localparam [63:0] EXP_P0_ADDR1  = 64'h0000_0000_0000_0080;
    localparam [31:0] EXP_P0_BSIZ1  = 32'd123;

    localparam integer EXP_P1_COUNT  = 2;
    localparam integer EXP_P1_SIZE   = 311;
    localparam [63:0] EXP_P1_ADDR0  = 64'h0000_0000_0000_4000;
    localparam [31:0] EXP_P1_BSIZ0  = 32'd122;
    localparam [63:0] EXP_P1_ADDR1  = 64'h0000_0000_0000_407f;
    localparam [31:0] EXP_P1_BSIZ1  = 32'd63;

    // -----------------------------------------------------------------------
    // Clock / reset
    // -----------------------------------------------------------------------
    reg clk  = 0;
    reg rstn = 0;
    always #1.667 clk = ~clk;   // ~300 MHz
    initial begin rstn = 0; #17; rstn = 1; end

    // -----------------------------------------------------------------------
    // DUT signals
    // -----------------------------------------------------------------------
    reg                          p0_clear, p0_start;
    reg  [AXI_ADDR_WIDTH-1:0]    p0_sstable_base;
    reg  [31:0]                  p0_sstable_size;
    wire                         p0_busy, p0_done, p0_error;
    wire [31:0]                  p0_count;
    wire [MAX_BLOCK_HANDLES*AXI_ADDR_WIDTH-1:0] p0_addr_vec;
    wire [MAX_BLOCK_HANDLES*32-1:0]             p0_size_vec;

    wire [AXI_ADDR_WIDTH-1:0] p0_araddr;
    wire [7:0] p0_arlen; wire [2:0] p0_arsize; wire [1:0] p0_arburst;
    wire p0_arvalid, p0_arready;
    wire [AXI_DATA_WIDTH-1:0] p0_rdata;
    wire [1:0] p0_rresp;
    wire p0_rlast, p0_rvalid, p0_rready;

    reg                          p1_clear, p1_start;
    reg  [AXI_ADDR_WIDTH-1:0]    p1_sstable_base;
    reg  [31:0]                  p1_sstable_size;
    wire                         p1_busy, p1_done, p1_error;
    wire [31:0]                  p1_count;
    wire [MAX_BLOCK_HANDLES*AXI_ADDR_WIDTH-1:0] p1_addr_vec;
    wire [MAX_BLOCK_HANDLES*32-1:0]             p1_size_vec;

    wire [AXI_ADDR_WIDTH-1:0] p1_araddr;
    wire [7:0] p1_arlen; wire [2:0] p1_arsize; wire [1:0] p1_arburst;
    wire p1_arvalid, p1_arready;
    wire [AXI_DATA_WIDTH-1:0] p1_rdata;
    wire [1:0] p1_rresp;
    wire p1_rlast, p1_rvalid, p1_rready;

    // -----------------------------------------------------------------------
    // DUT instances
    // -----------------------------------------------------------------------
    sstable_data_block_handle_emitter #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH), .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN), .MAX_INDEX_BYTES(MAX_INDEX_BYTES),
        .MAX_BLOCK_HANDLES(MAX_BLOCK_HANDLES)
    ) u_p0 (
        .clk(clk), .rstn(rstn), .clear(p0_clear), .start(p0_start),
        .sstable_base_addr(p0_sstable_base), .sstable_size(p0_sstable_size),
        .busy(p0_busy), .done(p0_done), .error(p0_error),
        .block_handle_count(p0_count),
        .block_addr_vec(p0_addr_vec), .block_size_vec(p0_size_vec),
        .m_axi_araddr(p0_araddr), .m_axi_arlen(p0_arlen),
        .m_axi_arsize(p0_arsize), .m_axi_arburst(p0_arburst),
        .m_axi_arvalid(p0_arvalid), .m_axi_arready(p0_arready),
        .m_axi_rdata(p0_rdata), .m_axi_rresp(p0_rresp),
        .m_axi_rlast(p0_rlast), .m_axi_rvalid(p0_rvalid),
        .m_axi_rready(p0_rready)
    );

    sstable_data_block_handle_emitter #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH), .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .MAX_BURST_LEN(MAX_BURST_LEN), .MAX_INDEX_BYTES(MAX_INDEX_BYTES),
        .MAX_BLOCK_HANDLES(MAX_BLOCK_HANDLES)
    ) u_p1 (
        .clk(clk), .rstn(rstn), .clear(p1_clear), .start(p1_start),
        .sstable_base_addr(p1_sstable_base), .sstable_size(p1_sstable_size),
        .busy(p1_busy), .done(p1_done), .error(p1_error),
        .block_handle_count(p1_count),
        .block_addr_vec(p1_addr_vec), .block_size_vec(p1_size_vec),
        .m_axi_araddr(p1_araddr), .m_axi_arlen(p1_arlen),
        .m_axi_arsize(p1_arsize), .m_axi_arburst(p1_arburst),
        .m_axi_arvalid(p1_arvalid), .m_axi_arready(p1_arready),
        .m_axi_rdata(p1_rdata), .m_axi_rresp(p1_rresp),
        .m_axi_rlast(p1_rlast), .m_axi_rvalid(p1_rvalid),
        .m_axi_rready(p1_rready)
    );

    // -----------------------------------------------------------------------
    // AXI RAM models  (each 32 KB; src1 data is pre-loaded at mem[0x4000])
    // -----------------------------------------------------------------------
    axi_ram_model #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH), .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(1), .MEM_BYTES(MEM_BYTES), .READ_LATENCY(2)
    ) mem_p0 (
        .clk(clk), .rstn(rstn),
        .s_axi_araddr(p0_araddr), .s_axi_arlen(p0_arlen),
        .s_axi_arsize(p0_arsize), .s_axi_arburst(p0_arburst),
        .s_axi_arid(1'b0), .s_axi_arvalid(p0_arvalid),
        .s_axi_arready(p0_arready), .s_axi_rdata(p0_rdata),
        .s_axi_rresp(p0_rresp), .s_axi_rlast(p0_rlast), .s_axi_rid(),
        .s_axi_rvalid(p0_rvalid), .s_axi_rready(p0_rready),
        .s_axi_awaddr({AXI_ADDR_WIDTH{1'b0}}), .s_axi_awlen(8'd0),
        .s_axi_awsize(3'd0), .s_axi_awburst(2'd0), .s_axi_awid(1'b0),
        .s_axi_awvalid(1'b0), .s_axi_awready(),
        .s_axi_wdata({AXI_DATA_WIDTH{1'b0}}),
        .s_axi_wstrb({(AXI_DATA_WIDTH/8){1'b0}}), .s_axi_wlast(1'b0),
        .s_axi_wvalid(1'b0), .s_axi_wready(),
        .s_axi_bresp(), .s_axi_bid(), .s_axi_bvalid(), .s_axi_bready(1'b0)
    );

    axi_ram_model #(
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH), .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .AXI_ID_WIDTH(1), .MEM_BYTES(MEM_BYTES), .READ_LATENCY(2)
    ) mem_p1 (
        .clk(clk), .rstn(rstn),
        .s_axi_araddr(p1_araddr), .s_axi_arlen(p1_arlen),
        .s_axi_arsize(p1_arsize), .s_axi_arburst(p1_arburst),
        .s_axi_arid(1'b0), .s_axi_arvalid(p1_arvalid),
        .s_axi_arready(p1_arready), .s_axi_rdata(p1_rdata),
        .s_axi_rresp(p1_rresp), .s_axi_rlast(p1_rlast), .s_axi_rid(),
        .s_axi_rvalid(p1_rvalid), .s_axi_rready(p1_rready),
        .s_axi_awaddr({AXI_ADDR_WIDTH{1'b0}}), .s_axi_awlen(8'd0),
        .s_axi_awsize(3'd0), .s_axi_awburst(2'd0), .s_axi_awid(1'b0),
        .s_axi_awvalid(1'b0), .s_axi_awready(),
        .s_axi_wdata({AXI_DATA_WIDTH{1'b0}}),
        .s_axi_wstrb({(AXI_DATA_WIDTH/8){1'b0}}), .s_axi_wlast(1'b0),
        .s_axi_wvalid(1'b0), .s_axi_wready(),
        .s_axi_bresp(), .s_axi_bid(), .s_axi_bvalid(), .s_axi_bready(1'b0)
    );

    // -----------------------------------------------------------------------
    // Scoreboard helpers
    // -----------------------------------------------------------------------
    integer pass_cnt, fail_cnt;

    task chk32;
        input [63:0] got;
        input [63:0] exp;
        input [127:0] label;
        begin
            if (got !== exp) begin
                $display("FAIL %0s: got=0x%016x  exp=0x%016x", label, got, exp);
                fail_cnt = fail_cnt + 1;
            end else begin
                $display("PASS %0s = 0x%x", label, got);
                pass_cnt = pass_cnt + 1;
            end
        end
    endtask

    // -----------------------------------------------------------------------
    // Stimulus
    // -----------------------------------------------------------------------
    integer t;

    initial begin
        p0_clear = 0; p0_start = 0;
        p1_clear = 0; p1_start = 0;
        p0_sstable_base = SRC0_BASE;
        p0_sstable_size = EXP_P0_SIZE;
        p1_sstable_base = SRC1_BASE;
        p1_sstable_size = EXP_P1_SIZE;
        pass_cnt = 0; fail_cnt = 0;

        @(posedge rstn); repeat(4) @(posedge clk); #1;

        // Load SSTable fixtures
        // src0: @00000000 in memh → mem_p0.mem[0..372]
        // src1: @00004000 in memh → mem_p1.mem[0x4000..0x4136]
        $readmemh("fixtures/src0_sstable_real.memh", mem_p0.mem);
        $readmemh("fixtures/src1_sstable_real.memh", mem_p1.mem);
        $display("Fixtures loaded.");

        // ---- TEST 1: SRC0 parser ------------------------------------------
        $display("\n=== TEST 1: SRC0 parser ===");
        p0_clear = 1; @(posedge clk); #1; p0_clear = 0;
        @(posedge clk); #1;
        p0_start = 1; @(posedge clk); #1; p0_start = 0;

        for (t = 0; t < 100000; t = t + 1) begin
            @(posedge clk);
            if (p0_done || p0_error) t = 100001;
        end
        if (!p0_done) begin $display("TIMEOUT or error p0"); $finish; end

        $display("p0 block_count=%0d", p0_count);
        chk32(p0_count,                            EXP_P0_COUNT,   "p0_count  ");
        chk32(p0_addr_vec[0*AXI_ADDR_WIDTH +: AXI_ADDR_WIDTH], EXP_P0_ADDR0, "p0_addr[0]");
        chk32(p0_size_vec[0*32 +: 32],             EXP_P0_BSIZ0,   "p0_size[0]");
        chk32(p0_addr_vec[1*AXI_ADDR_WIDTH +: AXI_ADDR_WIDTH], EXP_P0_ADDR1, "p0_addr[1]");
        chk32(p0_size_vec[1*32 +: 32],             EXP_P0_BSIZ1,   "p0_size[1]");

        repeat(4) @(posedge clk);

        // ---- TEST 2: SRC1 parser ------------------------------------------
        $display("\n=== TEST 2: SRC1 parser ===");
        p1_clear = 1; @(posedge clk); #1; p1_clear = 0;
        @(posedge clk); #1;
        p1_start = 1; @(posedge clk); #1; p1_start = 0;

        for (t = 0; t < 100000; t = t + 1) begin
            @(posedge clk);
            if (p1_done || p1_error) t = 100001;
        end
        if (!p1_done) begin $display("TIMEOUT or error p1"); $finish; end

        $display("p1 block_count=%0d", p1_count);
        chk32(p1_count,                            EXP_P1_COUNT,   "p1_count  ");
        chk32(p1_addr_vec[0*AXI_ADDR_WIDTH +: AXI_ADDR_WIDTH], EXP_P1_ADDR0, "p1_addr[0]");
        chk32(p1_size_vec[0*32 +: 32],             EXP_P1_BSIZ0,   "p1_size[0]");
        chk32(p1_addr_vec[1*AXI_ADDR_WIDTH +: AXI_ADDR_WIDTH], EXP_P1_ADDR1, "p1_addr[1]");
        chk32(p1_size_vec[1*32 +: 32],             EXP_P1_BSIZ1,   "p1_size[1]");

        repeat(4) @(posedge clk);

        // ---- TEST 3: SRC0 restart (idempotency) ---------------------------
        $display("\n=== TEST 3: SRC0 restart ===");
        p0_clear = 1; @(posedge clk); #1; p0_clear = 0;
        @(posedge clk); #1;
        p0_start = 1; @(posedge clk); #1; p0_start = 0;

        for (t = 0; t < 100000; t = t + 1) begin
            @(posedge clk);
            if (p0_done || p0_error) t = 100001;
        end
        if (!p0_done) begin $display("TIMEOUT restart"); $finish; end
        chk32(p0_count, EXP_P0_COUNT, "p0_restart_count");
        chk32(p0_addr_vec[0*AXI_ADDR_WIDTH +: AXI_ADDR_WIDTH], EXP_P0_ADDR0, "p0r_addr[0]");
        chk32(p0_size_vec[0*32 +: 32],             EXP_P0_BSIZ0, "p0r_size[0]");

        repeat(4) @(posedge clk);

        // ---- Summary -------------------------------------------------------
        $display("\n========================================");
        if (fail_cnt == 0)
            $display("ALL PASS  (%0d checks)", pass_cnt);
        else
            $display("RESULT: pass=%0d  FAIL=%0d", pass_cnt, fail_cnt);
        $display("========================================");
        $finish;
    end

    initial begin #2000000; $display("WATCHDOG TIMEOUT"); $finish; end

endmodule
