// Auto-generated by gen_stress_fixture.py — scenario 5: mixed
localparam integer STRESS_BLOCK0_BYTES  = 8693;
localparam integer STRESS_BLOCK1_BYTES  = 9481;
localparam integer STRESS_SRC0_ENTRIES  = 80;
localparam integer STRESS_SRC1_ENTRIES  = 80;
localparam integer STRESS_EXPECT_MERGED  = 128;
localparam integer STRESS_EXPECT_DROPPED = 32;
localparam integer STRESS_EXPECT_DECODED = 160;
